### ISSUE TITLE
ci: `expanded-phrase.test` fails randomly 

### ISSUE THREAD

**Issue by HashidaTKS** [groonga/groonga#1479]
### What is your problem?

ci: `expanded-phrase.test` fails randomly, It should alwalys success.

https://github.com/groonga/groonga/actions/runs/3859590335/jobs/6579339140

**Comment by HashidaTKS** [comment]
It seems that the trigger for failing tests is the following error.

https://github.com/groonga/groonga/actions/runs/3859590335/jobs/6579339140#step:13:2027

Maybe an IO problem...?

```
/usr/share/ruby/fileutils.rb:551:in `rename': No such file or directory @ rb_file_s_rename - (/root/.cache/red-datasets/sudachi-synonym-dictionary/synonyms.txt.partial, /root/.cache/red-datasets/sudachi-synonym-dictionary/synonyms.txt) (Errno::ENOENT)
	from /usr/share/ruby/fileutils.rb:551:in `block in mv'
	from /usr/share/ruby/fileutils.rb:1597:in `block in fu_each_src_dest'
	from /usr/share/ruby/fileutils.rb:1613:in `fu_each_src_dest0'
	from /usr/share/ruby/fileutils.rb:1595:in `fu_each_src_dest'
	from /usr/share/ruby/fileutils.rb:542:in `mv'
	from /usr/local/share/gems/gems/red-datasets-0.1.5/lib/datasets/downloader.rb:65:in `download'
	from /usr/local/share/gems/gems/red-datasets-0.1.5/lib/datasets/dataset.rb:38:in `download'
	from /usr/local/share/gems/gems/red-datasets-0.1.5/lib/datasets/sudachi-synonym-dictionary.rb:67:in `open_data'
	from /usr/local/share/gems/gems/red-datasets-0.1.5/lib/datasets/sudachi-synonym-dictionary.rb:34:in `each'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/sudachi.rb:34:in `each'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/groonga-generator.rb:35:in `generate'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/command-line/generator.rb:58:in `block (2 levels) in run'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/command-line/generator.rb:133:in `open_output'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/command-line/generator.rb:56:in `block in run'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/command-line/generator.rb:53:in `catch'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/lib/groonga-synonym/command-line/generator.rb:53:in `run'
	from /usr/local/share/gems/gems/groonga-synonym-1.0.0/bin/groonga-synonym-generate:21:in `<top (required)>'
	from /usr/local/bin/groonga-synonym-generate:25:in `load'
	from /usr/local/bin/groonga-synonym-generate:25:in `<main>'
```
