### ISSUE TITLE
ci: failed to resolve source metadata for docker.io/arm64v8/almalinux:8 and 9

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#1806]
### What happend?

In `package` and `test` CI, the following error happened at `build with docker` step.

ref: https://github.com/groonga/groonga/actions/runs/9705591558/job/26788067581

```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 935B done
#1 DONE 0.0s

#2 [auth] arm64v8/almalinux:pull token for registry-1.docker.io
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/arm64v8/almalinux:8
#3 ERROR: no match for platform in manifest: not found
------
 > [internal] load metadata for docker.io/arm64v8/almalinux:8:
------
Dockerfile:2
--------------------
   1 |     ARG FROM=almalinux:8
   2 | >>> FROM ${FROM}
   3 |     
   4 |     ARG DEBUG
--------------------
ERROR: failed to solve: arm64v8/almalinux:8: failed to resolve source metadata for docker.io/arm64v8/almalinux:8: no match for platform in manifest: not found
rake aborted!
Command failed with status (1): [docker build --cache-from ghcr.io/groonga/...]
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:190:in `docker_run'
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:492:in `block (2 levels) in yum_build'
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:489:in `block in yum_build'
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:488:in `each'
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:488:in `yum_build'
/home/runner/work/groonga/groonga/apache-arrow/dev/tasks/linux-packages/package-task.rb:519:in `block (2 levels) in define_yum_task'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => yum:build
(See full trace by running task with --trace)
```

### How to reproduce it

Re-run https://github.com/groonga/groonga/actions/runs/9705591558/job/26788067581

### Expected behavior

Succeed to build using `docker.io/arm64v8/almalinux:8 and 9`

### Environment

- OS: Ubuntu
- OS Version: 22.04.4 LTS
- Groonga version: 14.0.5

**Comment by otegami** [comment]
```
#3 [internal] load metadata for docker.io/arm64v8/almalinux:8
#3 ERROR: no match for platform in manifest: not found
```
arm64 が存在しないかを確認する

**Comment by otegami** [comment]
存在はする。
```
$ docker manifest inspect almalinux:8

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1029,
         "digest": "sha256:c811eb62d56e5099c2b40fa15f14689fb4265e116795451b2431887eb56843c9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 840,
         "digest": "sha256:5daf2edc578ff5a09a4974162cc7e0603d52bf099de9d7f9384776a8b496a69e",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1031,
         "digest": "sha256:b296953e1e241e31fdf025b73ae857e4bfd8eea15daa5a528faee7e577f5dbee",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 840,
         "digest": "sha256:fca4568a3b47a6339c06481da66977c63059d50eee84dd458ce446be5a4aea0f",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1033,
         "digest": "sha256:6758df91dea04b7987e6cea891faf1694786f6edcff9c5cf87b5de7e45a555c1",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 840,
         "digest": "sha256:ba5d820d5545546f60bf282126840baa9a9aea9c11e2136b8ee972838b525cef",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1029,
         "digest": "sha256:a8c7ddbbb64ada18f218dd5bcc89e362b120091bff2157f5da5125eef47a6408",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 840,
         "digest": "sha256:8da65aef2211a5976f5081d7bb86a87f145fa49da3916d801dc8d9d1082975cf",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

**Comment by otegami** [comment]
`--platform linux/arm64/v8 ` を指定してあげる必要がありそう。

```console
$ docker build --cache-from ghcr.io/groonga/groonga-package:groonga-almalinux-8-aarch64 --tag ghcr.io/groonga/groonga-package:groonga-almalinux-8-aarch64 --build-arg DEBUG=yes --build-arg FROM=arm64v8/almalinux:8 -f packages/yum/almalinux-8/Dockerfile --progress=plain .
#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 935B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/arm64v8/almalinux:8
#2 ERROR: no match for platform in manifest: not found
------
 > [internal] load metadata for docker.io/arm64v8/almalinux:8:
------
Dockerfile:2
--------------------
   1 |     ARG FROM=almalinux:8
   2 | >>> FROM ${FROM}
   3 |
   4 |     ARG DEBUG
--------------------
ERROR: failed to solve: arm64v8/almalinux:8: failed to resolve source metadata for docker.io/arm64v8/almalinux:8: no match for platform in manifest: not found
```

**Comment by otegami** [comment]
指定しないと Host の情報を参照してしまうので、失敗する。
- https://docs.docker.com/build/building/multi-platform/

**Comment by otegami** [comment]
下記で platform の情報を渡してあげるようにすると良さそう。

https://github.com/groonga/groonga/blob/df8855dba679c4d6417ab2a47b3591f75779e0d6/.github/workflows/package.yml#L289-L293

**Comment by otegami** [comment]
実現したいこと
- image をビルドする際に、`--platform linux/arm64` を渡したい。


下記のコマンドで、下の部分が呼ばれる。
```console
$ rake yum:build BUILD_DIR=build
```

https://github.com/apache/arrow/blob/890916306ce4ca799ac027f5bde4fe70eace7b27/dev/tasks/linux-packages/package-task.rb#L519

**Comment by komainu8** [comment]
多分↓でいけると思います。

```diff
diff --git a/packages/Rakefile b/packages/Rakefile
index 71a867ace..20738c57e 100644
--- a/packages/Rakefile
+++ b/packages/Rakefile
@@ -45,6 +45,8 @@ class GroongaPackageTask < PackagesGroongaOrgPackageTask
 
   def docker_build_options(os, architecture)
     [
+      "--platform",
+      "linux/arm64/v8",
       "--build-arg",
       "APACHE_ARROW_VERSION=#{detect_target_apache_arrow_version}",
     ]
```

```
docker build --cache-from ghcr.io/groonga/groonga-package:groonga-almalinux-8-aarch64 --tag ghcr.io/groonga/groonga-package:groonga-almalinux-8-aarch64 --build-arg DEBUG=yes --build-arg FROM=arm64v8/almalinux:8 --platform linux/arm64/v8 --build-arg APACHE_ARROW_VERSION=16.1.0 almalinux-8
```

**Comment by komainu8** [comment]
> 指定しないと Host の情報を参照してしまうので、失敗する。
> 
>     * https://docs.docker.com/build/building/multi-platform/

これだと、 https://github.com/groonga/groonga/actions/runs/9705564009/job/26791821937 も失敗しそうだけど失敗しないのが不思議です。

**Comment by komainu8** [comment]
急に失敗するようになったのは、GitHub Actionsで使っているUbuntuのイメージがバージョンアップしたからだろうか。

成功している時： https://github.com/groonga/groonga/actions/runs/9688435376/job/26735182232

```
  Image: ubuntu-22.04
  Version: 20240616.1.0
```

失敗している時： https://github.com/groonga/groonga/actions/runs/9705564009/job/26791822506

```
   Image: ubuntu-22.04
  Version: 20240624.1.0
```

**Comment by otegami** [comment]
https://github.com/groonga/groonga/issues/1806#issuecomment-2196183020

ありがとうございます！

https://github.com/apache/arrow/blob/890916306ce4ca799ac027f5bde4fe70eace7b27/dev/tasks/linux-packages/package-task.rb#L184

**Comment by komainu8** [comment]
Changelog
https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1

関係ありそうなのは↓だろうか？

```
Docker-Buildx 	0.15.0 ->	0.15.1
```

ただ、 関係ありそうな変更は無いように見える。 https://github.com/docker/buildx/releases/tag/v0.15.1

**Comment by komainu8** [comment]
Testでも同じ問題で落ちる。 https://github.com/komainu8/groonga/actions/runs/9707967952/job/26794132116

**Comment by komainu8** [comment]
https://github.com/groonga/groonga/blob/main/.github/workflows/package.yml#L330-L334 にも`--platform`が必要そう。

**Comment by otegami** [comment]
こんな感じで書いてみました。
```diff
diff --git a/packages/Rakefile b/packages/Rakefile
index 7521f5cda..ab06b6079 100644
--- a/packages/Rakefile
+++ b/packages/Rakefile
@@ -54,10 +54,12 @@ class GroongaPackageTask < PackagesGroongaOrgPackageTask
   end

   def docker_build_options(os, architecture)
-    [
-      "--build-arg",
-      "APACHE_ARROW_VERSION=#{detect_target_apache_arrow_version}",
-    ]
+    options = [
+                "--build-arg",
+                "APACHE_ARROW_VERSION=#{detect_target_apache_arrow_version}",
+              ]
+    options = options.merge(["--platform", "linux/arm64"]) if architecture == 'aarch64'
+    options
   end

   def apt_targets_default
```

**Comment by kou** [comment]
こういう感じじゃないかな。。。

```diff
diff --git a/packages/yum/almalinux-8-aarch64/from b/packages/yum/almalinux-8-aarch64/from
index dcefc318e..4187a13a1 100644
--- a/packages/yum/almalinux-8-aarch64/from
+++ b/packages/yum/almalinux-8-aarch64/from
@@ -1 +1 @@
-arm64v8/almalinux:8
+arm64v8/almalinux:8 --platform linux/arm64
```

**Comment by otegami** [comment]
ありがとうございますmm

---

📝 `from` ファイルの中に書くと下記で良い感じにやってくれる。

https://github.com/apache/arrow/blob/890916306ce4ca799ac027f5bde4fe70eace7b27/dev/tasks/linux-packages/package-task.rb#L162-L178

**Comment by otegami** [comment]
fix: https://github.com/groonga/groonga/pull/1807
