### ISSUE TITLE
大量のレコードがあるテーブルに対してgrn_ii_build2するとクラッシュする

### ISSUE THREAD

**Issue by kou** [groonga/groonga#546]
原因はわからないんですが、メモしておきます。

`GRN_ID_MAX`くらいのレコードを追加したテーブルに対して`grn_ii_build2`するとクラッシュしました。`GRN_ID_MAX`（11億弱）は公式の最大レコード数（2億強）よりだいぶ大きいけどそれのせいかしら。

`generate_data.rb`:

```ruby
puts "table_create Items TABLE_NO_KEY"
puts "column_create Items price COLUMN_SCALAR UInt64"

puts "load --table Items"
puts "["
(0x3fffffff - 9).times do |i|
  if i > 0
    puts ","
  end
  print "{\"price\": 100}"
end
puts
puts "]"

puts "table_create Prices TABLE_PAT_KEY UInt64"
puts "column_create Prices index COLUMN_INDEX Items price"
```

```text
% ruby b.rb | GRN_INDEX_CHUNK_SPLIT_ENABLE=yes /tmp/local/bin/groonga -n /tmp/db
*** Error in `/tmp/local/bin/groonga': free(): invalid size: 0x00007fbed9f26010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x71fe5)[0x7fc16dd44fe5]
/lib/x86_64-linux-gnu/libc.so.6(+0x77936)[0x7fc16dd4a936]
/lib/x86_64-linux-gnu/libc.so.6(+0x7811e)[0x7fc16dd4b11e]
/tmp/local/lib/libgroonga.so.0(grn_free_default+0x32)[0x7fc16f5f805c]
/tmp/local/lib/libgroonga.so.0(+0x20ef7b)[0x7fc16f7c0f7b]
/tmp/local/lib/libgroonga.so.0(+0x2114ee)[0x7fc16f7c34ee]
/tmp/local/lib/libgroonga.so.0(+0x211946)[0x7fc16f7c3946]
/tmp/local/lib/libgroonga.so.0(grn_ii_build2+0x7a)[0x7fc16f7ccc56]
/tmp/local/lib/libgroonga.so.0(grn_index_column_build+0x526)[0x7fc16f7cd5a8]
/tmp/local/lib/libgroonga.so.0(grn_index_column_rebuild+0x8d)[0x7fc16f7cdd47]
/tmp/local/lib/libgroonga.so.0(grn_obj_reindex+0x325)[0x7fc16f84d577]
/tmp/local/lib/libgroonga.so.0(+0x390d9f)[0x7fc16f942d9f]
/tmp/local/lib/libgroonga.so.0(grn_proc_call+0x426)[0x7fc16f68187d]
/tmp/local/lib/libgroonga.so.0(grn_command_run+0xce)[0x7fc16f60a500]
/tmp/local/lib/libgroonga.so.0(grn_expr_exec+0x1a5)[0x7fc16f681f99]
/tmp/local/lib/libgroonga.so.0(grn_ctx_qe_exec+0xf6b)[0x7fc16f612788]
/tmp/local/lib/libgroonga.so.0(grn_ctx_send+0x515)[0x7fc16f61330e]
/tmp/local/lib/libgroonga.so.0(grn_ctx_sendv+0x14b)[0x7fc16f612d4c]
/tmp/local/bin/groonga[0x405f3d]
/tmp/local/bin/groonga[0x41732f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fc16dcf3610]
/tmp/local/bin/groonga[0x4049a9]
======= Memory map: ========
00400000-0041e000 r-xp 00000000 08:05 655971                             /tmp/local/bin/groonga
...
```

バックトレースはこう。

```text
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ffff7fc4740 (LWP 19135)):
#0  0x00007ffff5d23478 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 19135
        selftid = 19135
#1  0x00007ffff5d248fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {
          __sigaction_handler = {
            sa_handler = 0x2020202020202020, 
            sa_sigaction = 0x2020202020202020
          }, 
          sa_mask = {
            __val =               {[0] = 2314885530818453536,
              [1] = 7886980662457016352,
              [2] = 7089843615423541104,
              [3] = 3688502177853091886,
              [4] = 7161961896622056238,
              [5] = 3256155514198047031,
              [6] = 3775203287669040695,
              [7] = 3276212736508309557,
              [8] = 3472609789223182451,
              [9] = 3832627295892287536,
              [10] = 2321385925519947296,
              [11] = 2314885530818453536,
              [12] = 2314885530818453536,
              [13] = 8101259050460651552,
              [14] = 3342344027367433263,
              [15] = 3329057537376923696}
          }, 
          sa_flags = 1714883171, 
          sa_restorer = 0x54
        }
        sigs = {
          __val =             {[0] = 32,
            [1] = 0 <repeats 15 times>}
---Type <return> to continue, or q <return> to quit---
        }
#2  0x00007ffff5d61fea in __libc_message (do_abort=do_abort@entry=2, 
    fmt=fmt@entry=0x7ffff5e59cd8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
        ap = <error reading variable ap (Attempt to dereference a generic pointer.)>
        fd = 24
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ffff5d67936 in malloc_printerr (action=3, 
    str=0x7ffff5e564dc "free(): invalid size", ptr=<optimized out>, 
    ar_ptr=<optimized out>) at malloc.c:5000
        buf =           "00007ffd61f43010"
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x7ffff5e564dc "free(): invalid size"
        action = 3
#4  0x00007ffff5d6811e in _int_free (av=0x7ffff608eb20 <main_arena>, 
    p=<optimized out>, have_lock=0) at malloc.c:3861
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ =           "_int_free"
#5  0x00007ffff76150ac in grn_free_default (ctx=0x7fffffffe000, 
    ptr=0x7ffd61f43010, file=0x7ffff7ac3f3c "ii.c", line=9212, 
    func=0x7ffff7ac7e90 <__FUNCTION__.18618> "grn_ii_builder_chunk_fin")
    at alloc.c:827
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ =           "grn_free_default"
#6  0x00007ffff77de01d in grn_ii_builder_chunk_fin (ctx=0x7fffffffe000, 
    chunk=0x1109400) at ii.c:9212
        __FUNCTION__ =           "grn_ii_builder_chunk_fin"
#7  0x00007ffff77e0590 in grn_ii_builder_fin (ctx=0x7fffffffe000, 
    builder=0x1108340) at ii.c:9586
        __FUNCTION__ =           "grn_ii_builder_fin"
#8  0x00007ffff77e09e8 in grn_ii_builder_close (ctx=0x7fffffffe000, 
    builder=0x1108340) at ii.c:9647
        rc = GRN_SUCCESS
        __FUNCTION__ =           "grn_ii_builder_close"
#9  0x00007ffff77e9cf8 in grn_ii_build2 (ctx=0x7fffffffe000, ii=0xad2680, 
    options=0x0) at ii.c:10820
        rc = GRN_SUCCESS
        rc_close = -134257328
        builder = 0x1108340
#10 0x00007ffff77ea64a in grn_index_column_build (ctx=0x7fffffffe000, 
    index_column=0xad2680) at index_column.c:145
        i = 0
        ncol = 1
        flags = 32769
        ii = 0xad2680
        tokenizer = 0x0
        use_grn_ii_build = 1 '\001'
        src = 0xad2490
        cp = 0xad2558
        col = 0xad2550
        target = 0x10fc9a0
        s = 0xad2724
        __FUNCTION__ =           "grn_index_column_build"
#11 0x00007ffff77eade9 in grn_index_column_rebuild (ctx=0x7fffffffe000, 
    index_column=0xad2680) at index_column.c:191
        ii = 0xad2680
#12 0x00007ffff786a619 in grn_obj_reindex (ctx=0x7fffffffe000, obj=0xad2680)
    at obj.c:421
        __FUNCTION__ =           "grn_obj_reindex"
#13 0x00007ffff795fdf6 in proc_reindex (ctx=0x7fffffffe000, nargs=0, 
    args=0x7ffff7e13038, user_data=0x7fffffff3220) at proc.c:3941
---Type <return> to continue, or q <return> to quit---
        target_name = 0x7ffff2cae828
        target = 0xad2680
        __FUNCTION__ =           "proc_reindex"
#14 0x00007ffff769e91f in grn_proc_call (ctx=0x7fffffffe000, proc=0xa6f430, 
    nargs=0, caller=0xa6f430) at expr.c:1398
        pctx = {
          user_data = {
            int_value = 0, 
            id = 0, 
            ptr = 0x0
          }, 
          proc = 0xa6f430, 
          caller = 0xa6f430, 
          hooks = 0x0, 
          currh = 0x0, 
          phase = (PROC_NEXT | unknown: 4158559916), 
          nargs = 32767, 
          offset = 0, 
          data =             {[0] = {
              int_value = 1, 
              id = 1, 
              ptr = 0x1
            },
            [1] = {
              int_value = 0, 
              id = 0, 
              ptr = 0x0
            },
            [2] = {
              int_value = 4213120, 
              id = 4213120, 
              ptr = 0x404980 <_start>
            },
            [3] = {
              int_value = -144870168, 
              id = 4150097128, 
              ptr = 0x7ffff75d74e8
            },
---Type <return> to continue, or q <return> to quit---
            [4] = {
              int_value = 0, 
              id = 0, 
              ptr = 0x0
            },
            [5] = {
              int_value = -52400, 
              id = 4294914896, 
              ptr = 0x7fffffff3350
            },
            [6] = {
              int_value = 4213120, 
              id = 4213120, 
              ptr = 0x404980 <_start>
            },
            [7] = {
              int_value = -136380304, 
              id = 4158586992, 
              ptr = 0x7ffff7df0070 <_dl_runtime_resolve+80>
            },
            [8] = {
              int_value = 1, 
              id = 1, 
              ptr = 0x1
            },
            [9] = {
              int_value = 0, 
              id = 0, 
              ptr = 0x0
            },
            [10] = {
              int_value = 10941488, 
              id = 10941488, 
              ptr = 0xa6f430
            },
            [11] = {
              int_value = -144876048, 
              id = 4150091248, 
---Type <return> to continue, or q <return> to quit---
              ptr = 0x7ffff75d5df0
            },
            [12] = {
              int_value = 0, 
              id = 0, 
              ptr = 0x0
            },
            [13] = {
              int_value = -8848, 
              id = 4294958448, 
              ptr = 0x7fffffffdd70
            },
            [14] = {
              int_value = 4213120, 
              id = 4213120, 
              ptr = 0x404980 <_start>
            },
            [15] = {
              int_value = -136380304, 
              id = 4158586992, 
              ptr = 0x7ffff7df0070 <_dl_runtime_resolve+80>
            }}
        }
        obj = 0x0
        args = 0x7ffff7e13038
        p = 0xa6f430
        __FUNCTION__ =           "grn_proc_call"
#15 0x00007ffff7627550 in grn_command_run (ctx=0x7fffffffe000, 
    command=0xa6f430, input=0xa0b830) at command.c:194
        stack_curr = 0
        proc = 0xa6f430
#16 0x00007ffff769f03b in grn_expr_exec (ctx=0x7fffffffe000, expr=0xa6f430, 
    nargs=0) at expr.c:2485
        input = 0xa0b830
        proc = 0xa6f430
        val = 0x0
        stack_curr = 0
        __FUNCTION__ =           "grn_expr_exec"
---Type <return> to continue, or q <return> to quit---
#17 0x00007ffff762f7d8 in grn_ctx_qe_exec (ctx=0x7fffffffe000, 
    str=0x7fffffffdf88 "reindex Prices.index", str_len=20) at ctx.c:1223
        command_version = GRN_COMMAND_VERSION_1
        tok_type = 1 '\001'
        offset = 1
        buf = {
          header = {
            type = 2 '\002', 
            impl_flags = 0 '\000', 
            flags = 12, 
            domain = 15
          }, 
          u = {
            b = {
              head = 0x692e736563697250 <error: Cannot access memory at address 0x692e736563697250>, 
              curr = 0x7865646e <error: Cannot access memory at address 0x7865646e>, 
              tail = 0x0
            }, 
            v = {
              body = 0x692e736563697250, 
              sections = 0x7865646e, 
              n_sections = 0
            }
          }
        }
        expr = 0xa6f430
        val = 0x7ffff2cae828
        request_id = {
          header = {
            type = 2 '\002', 
            impl_flags = 0 '\000', 
            flags = 0, 
            domain = 15
          }, 
          u = {
            b = {
---Type <return> to continue, or q <return> to quit---
              head = 0x0, 
              curr = 0x0, 
              tail = 0x0
            }, 
            v = {
              body = 0x0, 
              sections = 0x0, 
              n_sections = 0
            }
          }
        }
        request_timeout = 0
        p = 0x7fffffffdf9c ""
        e = 0x7fffffffdf9c ""
        v = 0x7fffffffddd8 "Prices.index"
        __FUNCTION__ =           "grn_ctx_qe_exec"
#18 0x00007ffff763035e in grn_ctx_send (ctx=0x7fffffffe000, 
    str=0x7fffffffdf88 "reindex Prices.index", str_len=20, flags=0)
    at ctx.c:1324
        expr = 0x0
        __FUNCTION__ =           "grn_ctx_send"
#19 0x00007ffff762fd9c in grn_ctx_sendv (ctx=0x7fffffffe000, argc=-1, 
    argv=0x7fffffffe4e8, flags=0) at ctx.c:1253
        buf = {
          header = {
            type = 2 '\002', 
            impl_flags = 0 '\000', 
            flags = 20, 
            domain = 15
          }, 
          u = {
            b = {
              head = 0x207865646e696572 <error: Cannot access memory at address 0x207865646e696572>, 
              curr = 0x692e736563697250 <error: Cannot access memory at address 0x692e736563697250>, 
              tail = 0x7865646e <error: Cannot access memory at address 0x7865646e>
---Type <return> to continue, or q <return> to quit---
            }, 
            v = {
              body = 0x207865646e696572, 
              sections = 0x692e736563697250, 
              n_sections = 2019910766
            }
          }
        }
#20 0x0000000000405f3d in do_alone (argc=2, argv=0x7fffffffe4d8)
    at groonga.c:408
        rc = GRN_SUCCESS
        command = {
          header = {
            type = 2 '\002', 
            impl_flags = 0 '\000', 
            flags = 0, 
            domain = 15
          }, 
          u = {
            b = {
              head = 0x0, 
              curr = 0x0, 
              tail = 0x0
            }, 
            v = {
              body = 0x0, 
              sections = 0x0, 
              n_sections = 0
            }
          }
        }
        exit_code = 1
        path = 0x7fffffffe885 "/tmp/db4/db"
        db = 0x7f5aa0
        ctx_ = {
          rc = GRN_SUCCESS, 
          flags = 0, 
          encoding = GRN_ENC_UTF8, 
---Type <return> to continue, or q <return> to quit---
          ntrace = 0 '\000', 
          errlvl = 6 '\006', 
          stat = 0 '\000', 
          seqno = 3, 
          subno = 6, 
          seqno2 = 0, 
          errline = 0, 
          user_data = {
            int_value = -8256, 
            id = 4294959040, 
            ptr = 0x7fffffffdfc0
          }, 
          prev = 0x61ede0 <grn_gctx>, 
          next = 0x7ffff7ddaac0 <grn_the_request_canceler_ctx>, 
          errfile = 0x7ffff7ab373f "", 
          errfunc = 0x7ffff7ab373f "", 
          impl = 0x7ffff7e11000, 
          trace =             {[0] = 0x0,
            [1] = 0x7ffff7de97a2 <_dl_fixup+482>,
            [2] = 0x404980 <_start>,
            [3] = 0x7ffff7dd51c0,
            [4] = 0x404980 <_start>,
            [5] = 0x7fffffffe4b0,
            [6] = 0x0,
            [7] = 0x61e5a0,
            [8] = 0x404980 <_start>,
            [9] = 0x7fffffffe4b0,
            [10] = 0x0,
            [11] = 0x0,
            [12] = 0x0,
            [13] = 0x7ffff7de96ad <_dl_fixup+237>,
            [14] = 0x1,
            [15] = 0x0}, 
          errbuf =             "\000\000\000\000\000\000\000\000\300\261]\367\377\177\000\000\000\000\000\000\000\000\000\000\320\343\377\377\377\177\000\000\200I@\000\000\000\000\000p\000\337\367\377\177", '\000' <repeats 26 times>, "PGz", '\000' <repeats 13 times>, "d\263\326\365\377\177\000\000\030\000\000\000\000\000\000\000p@\230\367\377\177\000\000\000\000\000\000\000\000\000\000@G\374\367\3---Type <return> to continue, or q <return> to quit---
77\177\000"
        }
        ctx = 0x7fffffffe000
#21 0x000000000041732f in main (argc=6, argv=0x7fffffffe4b8) at groonga.c:3717
        port_arg = 0x0
        encoding_arg = 0x0
        max_n_threads_arg = 0x0
        log_level_arg = 0x0
        bind_address_arg = 0x0
        hostname_arg = 0x0
        protocol_arg = 0x0
        log_path_arg = 0x7fffffffe878 "/tmp/db4/log"
        log_rotate_threshold_size_arg = 0x0
        query_log_path_arg = 0x0
        query_log_rotate_threshold_size_arg = 0x0
        cache_limit_arg = 0x0
        document_root_arg = 0x0
        default_command_version_arg = 0x0
        default_match_escalation_threshold_arg = 0x0
        input_fd_arg = 0x0
        output_fd_arg = 0x0
        working_directory_arg = 0x0
        config_path = 0x0
        default_request_timeout_arg = 0x0
        exit_code = 0
        i = 3
        flags = 16
        cache_limit = 0
        default_command_version = GRN_COMMAND_VERSION_1
        default_match_escalation_threshold = 0
        default_request_timeout = 0
        need_line_editor = 0 '\000'
        opts =           {[0] = {
            opt = 112 'p', 
            longopt = 0x41cfd2 "port", 
            arg = 0x7fffffffe2b8, 
            flag = 0, 
            op = GETOPT_OP_NONE
---Type <return> to continue, or q <return> to quit---
          },
          [1] = {
            opt = 101 'e', 
            longopt = 0x41cfd7 "encoding", 
            arg = 0x7fffffffe2b0, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [2] = {
            opt = 116 't', 
            longopt = 0x41cfe0 "max-threads", 
            arg = 0x7fffffffe2a8, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [3] = {
            opt = 104 'h', 
            longopt = 0x41cfec "help", 
            arg = 0x0, 
            flag = 1, 
            op = GETOPT_OP_UPDATE
          },
          [4] = {
            opt = 99 'c', 
            longopt = 0x0, 
            arg = 0x0, 
            flag = 32, 
            op = GETOPT_OP_ON
          },
          [5] = {
            opt = 100 'd', 
            longopt = 0x0, 
            arg = 0x0, 
            flag = 64, 
            op = GETOPT_OP_ON
          },
          [6] = {
            opt = 115 's', 
---Type <return> to continue, or q <return> to quit---
            longopt = 0x0, 
            arg = 0x0, 
            flag = 128, 
            op = GETOPT_OP_ON
          },
          [7] = {
            opt = 108 'l', 
            longopt = 0x41cff1 "log-level", 
            arg = 0x7fffffffe2a0, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [8] = {
            opt = 105 'i', 
            longopt = 0x41cffb "server-id", 
            arg = 0x7fffffffe290, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [9] = {
            opt = 110 'n', 
            longopt = 0x0, 
            arg = 0x0, 
            flag = 256, 
            op = GETOPT_OP_ON
          },
          [10] = {
            opt = 0 '\000', 
            longopt = 0x41d005 "protocol", 
            arg = 0x7fffffffe288, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [11] = {
            opt = 0 '\000', 
            longopt = 0x41d00e "version", 
            arg = 0x0, 
            flag = 2, 
---Type <return> to continue, or q <return> to quit---
            op = GETOPT_OP_UPDATE
          },
          [12] = {
            opt = 0 '\000', 
            longopt = 0x41d016 "log-path", 
            arg = 0x7fffffffe280, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [13] = {
            opt = 0 '\000', 
            longopt = 0x41d01f "log-rotate-threshold-size", 
            arg = 0x7fffffffe278, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [14] = {
            opt = 0 '\000', 
            longopt = 0x41d039 "query-log-path", 
            arg = 0x7fffffffe270, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [15] = {
            opt = 0 '\000', 
            longopt = 0x41d048 "query-log-rotate-threshold-size", 
            arg = 0x7fffffffe268, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [16] = {
            opt = 0 '\000', 
            longopt = 0x41d068 "pid-path", 
            arg = 0x61f068 <pid_file_path>, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [17] = {
---Type <return> to continue, or q <return> to quit---
            opt = 0 '\000', 
            longopt = 0x41b72c "config-path", 
            arg = 0x7fffffffe228, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [18] = {
            opt = 0 '\000', 
            longopt = 0x41d071 "show-config", 
            arg = 0x0, 
            flag = 3, 
            op = GETOPT_OP_UPDATE
          },
          [19] = {
            opt = 0 '\000', 
            longopt = 0x41d07d "cache-limit", 
            arg = 0x7fffffffe260, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [20] = {
            opt = 0 '\000', 
            longopt = 0x41d089 "file", 
            arg = 0x61f070 <input_path>, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [21] = {
            opt = 0 '\000', 
            longopt = 0x41d08e "document-root", 
            arg = 0x7fffffffe258, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [22] = {
            opt = 0 '\000', 
            longopt = 0x41d09c "default-command-version", 
            arg = 0x7fffffffe250, 
---Type <return> to continue, or q <return> to quit---
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [23] = {
            opt = 0 '\000', 
            longopt = 0x41d0b8 "default-match-escalation-threshold", 
            arg = 0x7fffffffe248, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [24] = {
            opt = 0 '\000', 
            longopt = 0x41d0db "bind-address", 
            arg = 0x7fffffffe298, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [25] = {
            opt = 0 '\000', 
            longopt = 0x41d0e8 "input-fd", 
            arg = 0x7fffffffe240, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [26] = {
            opt = 0 '\000', 
            longopt = 0x41d0f1 "output-fd", 
            arg = 0x7fffffffe238, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [27] = {
            opt = 0 '\000', 
            longopt = 0x41d0fb "working-directory", 
            arg = 0x7fffffffe230, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
---Type <return> to continue, or q <return> to quit---
          [28] = {
            opt = 0 '\000', 
            longopt = 0x41d10d "use-windows-event-log", 
            arg = 0x0, 
            flag = 512, 
            op = GETOPT_OP_ON
          },
          [29] = {
            opt = 0 '\000', 
            longopt = 0x41d123 "memcached-column", 
            arg = 0x61f090 <memcached_column_name>, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [30] = {
            opt = 0 '\000', 
            longopt = 0x41d134 "default-request-timeout", 
            arg = 0x7fffffffe220, 
            flag = 0, 
            op = GETOPT_OP_NONE
          },
          [31] = {
            opt = 0 '\000', 
            longopt = 0x0, 
            arg = 0x0, 
            flag = 0, 
            op = GETOPT_OP_NONE
          }}
```

データを入れた後は以下でも再現させられます。

```text
% GRN_INDEX_CHUNK_SPLIT_ENABLE=yes gdb --args /tmp/local/bin/groonga /tmp/db reindex Prices.index
```

**Comment by s-yata** [comment]
ご報告ありがとうございます．
まずは手元でも再現するか確認してみます．

**Comment by s-yata** [comment]
再現しました．

```
$ ruby generate_data.rb | GRN_INDEX_CHUNK_SPLIT_ENABLE=yes groonga -n db/db
[[0,1463101778.811284,0.0002045631408691406],true]
[[0,1463101778.811513,3.790855407714844e-05],true]
[[0,1463101778.811559,2708.320266246796],1073741814]
[[0,1463104487.13184,8.034706115722656e-05],true]
*** Error in `groonga': free(): invalid size: 0x00007f0804c78010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f0ada8e6725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7f0ada8eef4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f0ada8f2abc]
/usr/local/lib/libgroonga.so.0(grn_free_default+0x23)[0x7f0adb0cce63]
/usr/local/lib/libgroonga.so.0(grn_ii_build2+0x3e6)[0x7f0adb214b36]
...
```

**Comment by s-yata** [comment]
ちょうど一時ファイルのサイズが 2GiB を超えたところみたいなので（正確には 2,147,483,801 bytes）， 32-bit 整数を使っている箇所が問題になっていそうな気がします．
それから，同じ値について posting がとても長くなるときに起きるという可能性もありそうです．

**Comment by s-yata** [comment]
一時ファイルのサイズは関係ありませんでした．
ひとつの term に対する posting を構成する chunk の数が多くなり， buffer 直結の chunk に構成 chunk の一覧を書き込むところでバッファオーバーフローが起きていました．

buffer 直結の chunk がサイズ固定であったこと， chunk 数の想定が甘かったこと（おまけに chunk のサイズを小さめに調整したこと）が原因です．

**Comment by s-yata** [comment]
buffer 直結の chunk を可変長に変更し，クラッシュしなくなることを確認しました．

**Comment by kou** [comment]
さすがです！
