### ISSUE TITLE
Heroku にデプロイするとエラーが発生する(Rails, roonga使用)

### ISSUE THREAD

**Issue by ryota-sasabe** [groonga/groonga#609]
rroonga を使用した Rails アプリケーションを本日 Heroku にデプロイしたところ、下記のようなエラーが発生してしまいました。（昨日までは問題なかったと思います）

ログ
```
-----> Groonga app detected
-----> Loading environment variables
-----> Installing Groonga 6.1.0
curl --silent --remote-name --location https://github.com/groonga/groonga/releases/download/v6.1.0/heroku-groonga-6.1.0.tar.xz
tar xf heroku-groonga-6.1.0.tar.xz
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1451:in `unlink': No such file or directory @ unlink_internal - vendor/groonga/share/groonga/images (Errno::ENOENT)
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1451:in `block in remove_file'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1450:in `remove_file'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1439:in `remove'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:779:in `block in remove_entry'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1494:in `postorder_traverse'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:635:in `block in rm_r'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:631:in `each'
    from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:631:in `rm_r'
    from /app/tmp/buildpacks/fc86b9d773f342717ae0d11c3d8f0a0f19ceb04eca5ee9cd22c4719dfacfcbbfecda8a2a41d35c79b150363ff05f57910ebf28394991c11c4bdf5851bf076929/bin/compile:59:in `remove_needless_files'
    from /app/tmp/buildpacks/fc86b9d773f342717ae0d11c3d8f0a0f19ceb04eca5ee9cd22c4719dfacfcbbfecda8a2a41d35c79b150363ff05f57910ebf28394991c11c4bdf5851bf076929/bin/compile:100:in `block in <main>'
    from /app/tmp/buildpacks/fc86b9d773f342717ae0d11c3d8f0a0f19ceb04eca5ee9cd22c4719dfacfcbbfecda8a2a41d35c79b150363ff05f57910ebf28394991c11c4bdf5851bf076929/bin/compile:85:in `chdir'
    from /app/tmp/buildpacks/fc86b9d773f342717ae0d11c3d8f0a0f19ceb04eca5ee9cd22c4719dfacfcbbfecda8a2a41d35c79b150363ff05f57910ebf28394991c11c4bdf5851bf076929/bin/compile:85:in `<main>'
 !     Push rejected, failed to compile Groonga app.
 !     Push failed
```

ログの内容から、下記の箇所で例外が上がっていると推測しています。
https://github.com/groonga/heroku-buildpack-groonga/blob/58668361a5e9b097a0e204402c82caa622f10775/bin/compile#L59

**Comment by ryota-sasabe** [comment]
https://github.com/groonga/groonga/releases/download/v6.x.x/heroku-groonga-6.x.x.tar.xz
の中身を見ると、
`vendor/groonga/share/groonga/images` というディレクトリが、6.0.9 だと存在していたのですが、groonga 6.1.0 だと無くなっているようでした。
何か関連があるかもしれませんので、合わせて報告させていただきます。

**Comment by kou** [comment]
報告ありがとうございます！
たしかに、Groonga 6.1.0からそのディレクトリーを消したのでそれが原因だと思います。

ビルドバックを更新したのでもう一度試してみてもらえませんか？

**Comment by ryota-sasabe** [comment]
再度 Heroku デプロイしたところ、今度は問題なく処理できました！
とても早く対応いただいて助かりました。ありがとうございました！

**Comment by kou** [comment]
確認ありがとうございます！
これからもなにか問題があったら共有してもらえると助かります！
