### ISSUE TITLE
Crash when executing ruby_eval "."

### ISSUE THREAD

**Issue by ryo-pinus** [groonga/groonga#751]
**Description**

Crash when executing ruby_eval ".".

**Command**

```
[ryo@localhost ~]$ groonga --version
Groonga 7.0.5 [linux-gnu,x86_64,utf8,match-escalation-threshold=0,nfkc,mecab,msgpack,mruby,onigmo,zlib,lz4,zstd,epoll]

configure options: < '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--with-package-platform=centos7' '--with-mecab' '--with-munin-plugins' '--enable-mruby' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'>

[ryo@localhost ~]$ groonga
> plugin_register ruby/eval
[[0,1502005690.273513,0.0004255771636962891],true]
> ruby_eval "."
line 1:1: syntax error, unexpected '.'
中止 (コアダンプ)
```

**BackTrace**

```
[ryo@localhost ~]$ gdb --core core.13603 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
[New LWP 13603]
Reading symbols from /usr/bin/groonga...Reading symbols from /usr/lib/debug/usr/bin/groonga.debug...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `groonga'.
Program terminated with signal 6, Aborted.
#0  0x00007fc9a830d1d7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007fc9a830d1d7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc9a830e8c8 in __GI_abort () at abort.c:90
#2  0x00007fc9a9c11093 in segv_handler (signal_number=<optimized out>, info=<optimized out>, context=<optimized out>)
    at ctx.c:1606
#3  <signal handler called>
#4  mrb_irep_incref (mrb=mrb@entry=0x23d2fa0, irep=irep@entry=0x0) at ../mruby-source/src/state.c:125
#5  0x00007fc9a9f0ac94 in mrb_proc_new (mrb=mrb@entry=0x23d2fa0, irep=0x0) at ../mruby-source/src/proc.c:32
#6  0x00007fc9a9f29837 in mrb_generate_code (mrb=mrb@entry=0x23d2fa0, p=p@entry=0x25537e0)
    at ../mruby-source/mrbgems/mruby-compiler/core/codegen.c:2985
#7  0x00007fc9a9e9d1a0 in eval_context_compile (mrb=0x23d2fa0, self=...) at mrb_eval_context.c:41
#8  0x00007fc9a9f19409 in mrb_vm_exec (mrb=mrb@entry=0x23d2fa0, proc=0x254c620, pc=0x256438c)
    at ../mruby-source/src/vm.c:1265
#9  0x00007fc9a9f1c65c in mrb_vm_run (mrb=mrb@entry=0x23d2fa0, proc=proc@entry=0x24fd710, self=..., 
    stack_keep=<optimized out>) at ../mruby-source/src/vm.c:821
#10 0x00007fc9a9f1515e in mrb_run (mrb=mrb@entry=0x23d2fa0, proc=proc@entry=0x24fd710, self=...)
    at ../mruby-source/src/vm.c:2617
#11 0x00007fc9a9f1556e in mrb_funcall_with_block (mrb=mrb@entry=0x23d2fa0, self=..., mid=mid@entry=1897, 
    argc=<optimized out>, argc@entry=1, argv=argv@entry=0x7ffde9d6c1d0, blk=blk@entry=...)
    at ../mruby-source/src/vm.c:448
#12 0x00007fc9a9f15c53 in mrb_funcall_with_block (mrb=mrb@entry=0x23d2fa0, self=..., mid=1897, argc=1, 
    argv=0x7ffde9d6c1d0, blk=...) at ../mruby-source/src/vm.c:359
#13 0x00007fc9a9f15d4a in mrb_funcall_argv (mrb=mrb@entry=0x23d2fa0, self=..., mid=<optimized out>, 
    argc=<optimized out>, argv=<optimized out>) at ../mruby-source/src/vm.c:458
#14 0x00007fc9a9f15e30 in mrb_funcall (mrb=mrb@entry=0x23d2fa0, self=..., name=name@entry=0x7fc9a9fb755d "run_internal", 
    argc=argc@entry=1) at ../mruby-source/src/vm.c:344
#15 0x00007fc9a9e991ed in mrb_grn_command_run_wrapper (ctx=0x7ffde9d6e060, command=0x251ef00, input=<optimized out>, 
    user_data=<optimized out>) at mrb_command.c:89
#16 0x00007fc9a9c0f02c in grn_command_run (ctx=0x7ffde9d6e060, command=<optimized out>, input=<optimized out>)
    at command.c:189
#17 0x00007fc9a9c7372a in grn_expr_exec (ctx=<optimized out>, expr=<optimized out>, nargs=<optimized out>) at expr.c:2610
#18 0x00007fc9a9c13f63 in grn_ctx_qe_exec (ctx=ctx@entry=0x7ffde9d6e060, 
    str=str@entry=0x2572020 "ruby_eval \".\"\nr ruby/eval\nW\002", str_len=str_len@entry=13) at ctx.c:1254
#19 0x00007fc9a9c14b2f in grn_ctx_send (ctx=ctx@entry=0x7ffde9d6e060, 
    str=0x2572020 "ruby_eval \".\"\nr ruby/eval\nW\002", str_len=13, flags=<optimized out>, flags@entry=0) at ctx.c:1360
#20 0x0000000000406048 in do_alone (argv=<optimized out>, argc=<optimized out>) at groonga.c:401
#21 main (argc=<optimized out>, argv=<optimized out>) at groonga.c:3755
```

**Comment by komainu8** [comment]
@ryo-pinus 原因箇所まで調査いただきありがとうございます。こちらの環境でも再現しました。
他のプロジェクトにコミットするチャンスなので、エラー処理を追加してPullRequestしてみませんか？
